const PortfolioData= [
    {
        id:1,
        img:'./assets/portfolio/ecom.jpg',
        title:'Freshmir',
        category:'food website',
        language:'HTML5, CSS, Django',
        webLink:'https://github.com/dev-dauth2026/Freshmirhut',
        github:'https://github.com/dev-dauth2026/Freshmirhut',
    },
    {
        id:2,
        img:'./assets/portfolio/ecom.jpg',
        title:'BakerWindow Cleaning',
        category:'Window Cleaning website',
        language:'HTML5, CSS, JS',
        webLink:'https://github.com/dev-dauth2026/BakerWCleaning',
        github:'https://github.com/dev-dauth2026/BakerWCleaning',
    },
    {
        id:3,
        img:'./assets/portfolio/ecom.jpg',
        title:'ToDo List',
        category:'React todolist',
        language:'HTML5, CSS, React',
        webLink:'https://github.com/dev-dauth2026/React-ToDo-List-V2',
        github:'https://github.com/dev-dauth2026/React-ToDo-List-V2',
    },
    {
        id:4,
        img:'./assets/portfolio/ecom.jpg',
        title:'We Are Star',
        category:'Talentshow website',
        language:'HTML5, CSS, JS, PHP, MySQL',
        webLink:'https://github.com/dev-dauth2026/wearestars',
        github:'https://github.com/dev-dauth2026/wearestars',
    },
    {
        id:5,
        img:'./assets/portfolio/ecom.jpg',
        title:'GoogleKeep',
        category:'Note website',
        language:'HTML5, CSS, React',
        webLink:'https://github.com/dev-dauth2026/googlekeep',
        github:'https://github.com/dev-dauth2026/googlekeep',
    },
    {
        id:6,
        img:'./assets/portfolio/ecom.jpg',
        title:'Student Budget',
        category:'Renting website',
        language:'HTML5, CSS, Bootstrap, Django',
        webLink:'https://github.com/dev-dauth2026/StudentBudget',
        github:'https://github.com/dev-dauth2026/StudentBudget',
    },
    {
        id:7,
        img:'./assets/portfolio/ecom.jpg',
        title:'React Weather App',
        category:'weather website',
        language:'HTML5, CSS, React',
        webLink:'https://github.com/dev-dauth2026/reactweatherapp',
        github:'https://github.com/dev-dauth2026/reactweatherapp',
    },

]
export default PortfolioData;