const ItemData=[
    {
        id:1,
        language:'./assets/skill/html5.png',
        level:95,
    },
    {
        id:2,
        language:'./assets/skill/css3.png',
        level:85,
    },
    {
        id:3,
        language:'./assets/skill/bootstrap.png',
        level:80,
    },
    {
        id:4,
        language:'./assets/skill/material-ui.png',
        level:40,
    },
    {
        id:5,
        language:'./assets/skill/js.png',
        level:60,
    },
    {
        id:6,
        language:'./assets/skill/react.png',
        level:65,
    },
    {
        id:7,
        language:'./assets/skill/python.png',
        level:40,
    },
    {
        id:8,
        language:'./assets/skill/django.png',
        level:70,
    },
    {
        id:9,
        language:'./assets/skill/php.png',
        level:30,
    },
    {
        id:10,
        language:'./assets/skill/mysql.png',
        level:40,
    },
    {
        id:11,
        language:'./assets/skill/github.png',
        level:50,
    },
]
export default ItemData;